

[env:upesy_wroom]
platform = espressif32
board = upesy_wroom
framework = arduino
monitor_speed = 115200
lib_deps = 
	adafruit/DHT sensor library@^1.4.7
	mobizt/FirebaseClient@^2.2.9
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	adafruit/RTClib@^2.1.4
	bblanchon/ArduinoJson@^7.2.2
	knolleary/PubSubClient@^2.8  

upload_protocol = espota
; upload_port = ESP32-Echo.local
upload_port = esp32 ip
; OTA credentials passed as build flags
build_flags =
  -D OTA_HOST="\" \""
  -D OTA_PASSWORD="\" \""

upload_flags =
  --auth=Piyush@1


; IMPORTANT for OTA memory
board_build.partitions = min_spiffs.csv