; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:upesy_wroom]
platform = espressif32
board = upesy_wroom
framework = arduino
monitor_speed = 115200
lib_deps = 
	adafruit/DHT sensor library@^1.4.7
	mobizt/FirebaseClient@^2.2.9
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	adafruit/RTClib@^2.1.4
	bblanchon/ArduinoJson@^7.2.2
	knolleary/PubSubClient@^2.8  

upload_protocol = espota
; upload_port = ESP32-Echo.local
upload_port = 192.168.135.35
; OTA credentials passed as build flags
build_flags =
  -D OTA_HOST="\"ESP32-Echo\""
  -D OTA_PASSWORD="\"Piyush@1\""

upload_flags =
  --auth=Piyush@1


; IMPORTANT for OTA memory
board_build.partitions = min_spiffs.csv